/*
 Conçu par:
 Jean-François Èlie
 Ricardo Solon
 Eric Tremblay
 */
package sortie;

import javax.swing.JFrame;

public class InterfaceGraphique extends javax.swing.JFrame implements InterfaceUtilisateur {

    private Boolean etatBoutonDemarrer = false;
    private Boolean etatBoutonArreter = false;
    private Boolean etatBoutonPlus = false;
    private Boolean etatBoutonMoins = false;
    private Boolean etatBoutonFermerLogiciel = false;
    private int etatMolette = 0;    
    private Boolean demarrage = true;

    public InterfaceGraphique() {
       
        initComponents();
        ambianceVisuelle();
        this.setLocationRelativeTo(null);  //Centre la fenêtre
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
    }

    @Override
    public void allumerLedTempo() {
        lLedTempo.setBackground(new java.awt.Color(51, 255, 51)); 
    }
    
    
    @Override
    public void eteindreLedTempo() {
         lLedTempo.setBackground(new java.awt.Color(0, 55, 0));
    }
    
    @Override
    public void allumerLedMesure() {
        lLedMesure.setBackground(new java.awt.Color(255, 0, 0)); 
    }
    
    
    @Override
    public void eteindreLedMesure() {
         lLedMesure.setBackground(new java.awt.Color(60, 0, 0));
    }
    
    
    @Override
    public void afficherEcran(int tempo, int mesure){
        
        lTempo.setText(""+tempo);
        lMesure.setText(""+mesure);
        
        //Si demarrage du logiciel, met la molette a la
        //valeur du tempo dans la base de donnees.
        if(demarrage){
            demarrage = false;
            sMolette.setValue(tempo);
        }
        
    }
    
    @Override
    public void emettreSon(){
        java.awt.Toolkit.getDefaultToolkit().beep();
    }
    
    private void ambianceVisuelle(){
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        PaneauPrincipal = new javax.swing.JPanel();
        lLedTempo = new javax.swing.JLabel();
        lLedMesure = new javax.swing.JLabel();
        bDemarrer = new javax.swing.JButton();
        bArreter = new javax.swing.JButton();
        bMesureAugmenter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bMesureDiminuer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lTempo = new javax.swing.JLabel();
        lMesure = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sMolette = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setName("InterfaceGraphique"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fermeture_suavegarde(evt);
            }
        });

        PaneauPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PaneauPrincipal.setPreferredSize(new java.awt.Dimension(871, 420));

        lLedTempo.setBackground(new java.awt.Color(76, 96, 76));
        lLedTempo.setOpaque(true);

        lLedMesure.setBackground(new java.awt.Color(76, 96, 76));
        lLedMesure.setOpaque(true);

        bDemarrer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bDemarrer.setText("Démarrer");
        bDemarrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boutonPresser(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boutonLibere(evt);
            }
        });

        bArreter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bArreter.setText("Arrêter");
        bArreter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boutonPresser(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boutonLibere(evt);
            }
        });

        bMesureAugmenter.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bMesureAugmenter.setText("+");
        bMesureAugmenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boutonPresser(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boutonLibere(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mesure");
        jLabel3.setPreferredSize(new java.awt.Dimension(47, 14));

        bMesureDiminuer.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bMesureDiminuer.setText("-");
        bMesureDiminuer.setActionCommand("+");
        bMesureDiminuer.setMaximumSize(new java.awt.Dimension(47, 37));
        bMesureDiminuer.setMinimumSize(new java.awt.Dimension(47, 37));
        bMesureDiminuer.setPreferredSize(new java.awt.Dimension(47, 37));
        bMesureDiminuer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boutonPresser(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boutonLibere(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Tempo");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Mesure");

        lTempo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTempo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lTempo.setMaximumSize(new java.awt.Dimension(100, 60));
        lTempo.setMinimumSize(new java.awt.Dimension(100, 60));
        lTempo.setPreferredSize(new java.awt.Dimension(100, 60));

        lMesure.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lMesure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMesure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lMesure.setMaximumSize(new java.awt.Dimension(100, 60));
        lMesure.setMinimumSize(new java.awt.Dimension(100, 60));
        lMesure.setPreferredSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lMesure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMesure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jLabel9.setBackground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/speakerMod.jpg"))); // NOI18N
        jLabel9.setName("ISpeaker"); // NOI18N
        jLabel9.setOpaque(true);

        sMolette.setMaximum(208);
        sMolette.setMinimum(40);
        sMolette.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ecouteurMolette(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("40");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("molette");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("50");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("60");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("80");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("100");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("126");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("144");
        jLabel16.setToolTipText("");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("208");

        javax.swing.GroupLayout PaneauPrincipalLayout = new javax.swing.GroupLayout(PaneauPrincipal);
        PaneauPrincipal.setLayout(PaneauPrincipalLayout);
        PaneauPrincipalLayout.setHorizontalGroup(
            PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel15)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel16)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel17))
                    .addComponent(sMolette, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addGap(36, 36, 36)
                .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                        .addComponent(lLedTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lLedMesure, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneauPrincipalLayout.createSequentialGroup()
                                .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bMesureAugmenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bMesureDiminuer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(bArreter))
                                .addComponent(bDemarrer)))))
                .addGap(0, 54, Short.MAX_VALUE))
        );
        PaneauPrincipalLayout.setVerticalGroup(
            PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                        .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLedTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lLedMesure, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneauPrincipalLayout.createSequentialGroup()
                        .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bDemarrer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bArreter))
                        .addGap(25, 25, 25)
                        .addComponent(bMesureAugmenter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bMesureDiminuer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGap(30, 30, 30)
                .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(sMolette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneauPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addComponent(jLabel17))
                .addGap(0, 76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PaneauPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PaneauPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonPresser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonPresser
        
        if(evt.getSource() == bDemarrer){
            etatBoutonDemarrer = true;
        } else if (evt.getSource() == bArreter){
            etatBoutonArreter = true;
        } else if (evt.getSource() == bMesureAugmenter){
            etatBoutonPlus = true;
        }else if (evt.getSource() ==  bMesureDiminuer){
            etatBoutonMoins = true;
        }
                        
    }//GEN-LAST:event_boutonPresser

    private void ecouteurMolette(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ecouteurMolette
        
        if(evt.getSource() ==  sMolette){
            etatMolette = sMolette.getValue();
        }
    }//GEN-LAST:event_ecouteurMolette

    private void boutonLibere(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonLibere
       
        if(evt.getSource() == bDemarrer){
            etatBoutonDemarrer = false;
        } else if (evt.getSource() == bArreter){
            etatBoutonArreter = false;
        } else if (evt.getSource() == bMesureAugmenter){
            etatBoutonPlus = false;
        }else if (evt.getSource() ==  bMesureDiminuer){
            etatBoutonMoins = false;
        }
        
    }//GEN-LAST:event_boutonLibere

    private void fermeture_suavegarde(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fermeture_suavegarde

        etatBoutonFermerLogiciel = true;
        
    }//GEN-LAST:event_fermeture_suavegarde

    @Override
    public boolean getEtatDemarrer(){
        return etatBoutonDemarrer;
    }
    
    
    @Override
    public boolean getEtatArreter(){
        return etatBoutonArreter;
    }
    
    @Override
    public boolean getEtatPlus(){
        return etatBoutonPlus;
    }
    
    
    @Override
    public boolean getEtatMoins(){
        return etatBoutonMoins;
    }
    
    
    @Override
    public int getMolette(){
        return etatMolette;
    }
    
    @Override
    public boolean getEtatBoutonFermerLogiciel(){
        return etatBoutonFermerLogiciel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneauPrincipal;
    private javax.swing.JButton bArreter;
    private javax.swing.JButton bDemarrer;
    private javax.swing.JButton bMesureAugmenter;
    private javax.swing.JButton bMesureDiminuer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lLedMesure;
    protected javax.swing.JLabel lLedTempo;
    private javax.swing.JLabel lMesure;
    private javax.swing.JLabel lTempo;
    private javax.swing.JSlider sMolette;
    // End of variables declaration//GEN-END:variables
}
